### ISSUE TITLE
Small problem 

### ISSUE THREAD

**Issue by luxysiv** [jacobgelling/cloudflare-gateway-block-ads#1]
While rewriting your script to python, I discovered a small problem

`list_counter=1` will be make fail create lists if `chunk lists` > `cloudflare current lists` > `1`

I think  change to `list_counter = current_lists_count + 1` is better 
Sorry about my English and thanks for your creations

**Comment by jacobgelling** [comment]
Hi,

Maybe I'm misunderstanding but I think it's correct that ```list_counter=1```.

```list_counter``` is to keep track of the next list name, so it starts as "Block ads - 001".

First the code overwrites the existing lists. Here it doesn't use ```list_counter```, it only updates with each list to ```list_counter += 1```: https://github.com/jacobgelling/cloudflare-gateway-block-ads/blob/b3167d6d520db26999811b5edd8f34b69078385b/block_ads.sh#L81-L127

Then checks if more lists need creating (when ```chunk lists``` > ```cloudflare current lists``` > 1). It names the new list using ```list_counter```: https://github.com/jacobgelling/cloudflare-gateway-block-ads/blob/b3167d6d520db26999811b5edd8f34b69078385b/block_ads.sh#L129-L157

Finally it checks if lists need deleting (when ```chunk lists``` < ```cloudflare current lists```): https://github.com/jacobgelling/cloudflare-gateway-block-ads/blob/b3167d6d520db26999811b5edd8f34b69078385b/block_ads.sh#L246-L252

**Comment by luxysiv** [comment]
Oh, sorry. My mistake

**Comment by luxysiv** [comment]
I completed convert your repository. Please visit to see
```
https://github.com/luxysiv/ads
```

Thanks alot for your work
